title: Aman Kapoor
description: Writing and notes.
url: "https://amankapoor.github.io"
baseurl: ""

theme: minima
permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
